/**
 * Liste des codes OACI des pays
 * Basée sur https://fr.wikipedia.org/wiki/Code_OACI_des_aéroports
 * 
 * Structure:
 * - key: code OACI (2 lettres)
 * - name: nom du pays en français
 * - code: code ISO à 2 lettres pour affichage du drapeau
 */

interface CountryOACI {
  name: string;
  code: string; // Code ISO à 2 lettres pour les drapeaux
}

export const countriesOACI: Record<string, CountryOACI> = {
  // Europe (L)
  'LA': { name: 'Albanie', code: 'AL' },
  'LB': { name: 'Bulgarie', code: 'BG' },
  'LC': { name: 'Chypre', code: 'CY' },
  'LD': { name: 'Croatie', code: 'HR' },
  'LE': { name: 'Espagne', code: 'ES' },
  'LF': { name: 'France', code: 'FR' },
  'LG': { name: 'Grèce', code: 'GR' },
  'LH': { name: 'Hongrie', code: 'HU' },
  'LI': { name: 'Italie', code: 'IT' },
  'LJ': { name: 'Slovénie', code: 'SI' },
  'LK': { name: 'Tchéquie', code: 'CZ' },
  'LL': { name: 'Israël', code: 'IL' },
  'LM': { name: 'Malte', code: 'MT' },
  'LN': { name: 'Monaco', code: 'MC' },
  'LO': { name: 'Autriche', code: 'AT' },
  'LP': { name: 'Portugal', code: 'PT' },
  'LQ': { name: 'Bosnie-Herzégovine', code: 'BA' },
  'LR': { name: 'Roumanie', code: 'RO' },
  'LS': { name: 'Suisse', code: 'CH' },
  'LT': { name: 'Turquie', code: 'TR' },
  'LU': { name: 'Moldavie', code: 'MD' },
  'LV': { name: 'Palestine', code: 'PS' },
  'LW': { name: 'Macédoine du Nord', code: 'MK' },
  'LX': { name: 'Gibraltar', code: 'GI' },
  'LY': { name: 'Serbie/Monténégro', code: 'RS' },
  'LZ': { name: 'Slovaquie', code: 'SK' },
  
  // Europe du Nord (E)
  'EB': { name: 'Belgique', code: 'BE' },
  'ED': { name: 'Allemagne (civil)', code: 'DE' },
  'EE': { name: 'Estonie', code: 'EE' },
  'EF': { name: 'Finlande', code: 'FI' },
  'EG': { name: 'Royaume-Uni', code: 'GB' },
  'EH': { name: 'Pays-Bas', code: 'NL' },
  'EI': { name: 'Irlande', code: 'IE' },
  'EK': { name: 'Danemark', code: 'DK' },
  'EL': { name: 'Luxembourg', code: 'LU' },
  'EN': { name: 'Norvège', code: 'NO' },
  'EP': { name: 'Pologne', code: 'PL' },
  'ES': { name: 'Suède', code: 'SE' },
  'ET': { name: 'Allemagne (militaire)', code: 'DE' },
  'EV': { name: 'Lettonie', code: 'LV' },
  'EY': { name: 'Lituanie', code: 'LT' },
  
  // Asie & Moyen-Orient (O, R, V, U)
  'OA': { name: 'Afghanistan', code: 'AF' },
  'OB': { name: 'Bahreïn', code: 'BH' },
  'OD': { name: 'Yémen', code: 'YE' },
  'OE': { name: 'Arabie saoudite', code: 'SA' },
  'OI': { name: 'Iran', code: 'IR' },
  'OJ': { name: 'Jordanie', code: 'JO' },
  'OK': { name: 'Koweït', code: 'KW' },
  'OL': { name: 'Liban', code: 'LB' },
  'OM': { name: 'Émirats arabes unis', code: 'AE' },
  'OO': { name: 'Oman', code: 'OM' },
  'OP': { name: 'Pakistan', code: 'PK' },
  'OR': { name: 'Irak', code: 'IQ' },
  'OS': { name: 'Syrie', code: 'SY' },
  'OT': { name: 'Qatar', code: 'QA' },
  'OY': { name: 'Yémen', code: 'YE' },
  'RC': { name: 'Taïwan', code: 'TW' },
  'RJ': { name: 'Japon', code: 'JP' },
  'RK': { name: 'Corée du Sud', code: 'KR' },
  'RO': { name: 'Japon', code: 'JP' },
  'RP': { name: 'Philippines', code: 'PH' },
  'VA': { name: 'Inde (Ouest)', code: 'IN' },
  'VC': { name: 'Sri Lanka', code: 'LK' },
  'VD': { name: 'Cambodge', code: 'KH' },
  'VE': { name: 'Inde (Est)', code: 'IN' },
  'VG': { name: 'Bangladesh', code: 'BD' },
  'VH': { name: 'Hong Kong', code: 'HK' },
  'VI': { name: 'Inde (Nord)', code: 'IN' },
  'VL': { name: 'Laos', code: 'LA' },
  'VM': { name: 'Macao', code: 'MO' },
  'VN': { name: 'Népal', code: 'NP' },
  'VO': { name: 'Inde (Sud)', code: 'IN' },
  'VQ': { name: 'Bhoutan', code: 'BT' },
  'VR': { name: 'Maldives', code: 'MV' },
  'VT': { name: 'Thaïlande', code: 'TH' },
  'VV': { name: 'Viêt Nam', code: 'VN' },
  'VY': { name: 'Myanmar (Birmanie)', code: 'MM' },
  'UA': { name: 'Kazakhstan/Kirghizistan', code: 'KZ' },
  'UB': { name: 'Azerbaïdjan', code: 'AZ' },
  'UD': { name: 'Arménie', code: 'AM' },
  'UE': { name: 'Russie', code: 'RU' },
  'UG': { name: 'Géorgie', code: 'GE' },
  'UH': { name: 'Russie', code: 'RU' },
  'UI': { name: 'Russie', code: 'RU' },
  'UK': { name: 'Ukraine', code: 'UA' },
  'UL': { name: 'Russie', code: 'RU' },
  'UM': { name: 'Biélorussie/Russie', code: 'BY' },
  'UN': { name: 'Russie', code: 'RU' },
  'UO': { name: 'Russie', code: 'RU' },
  'UR': { name: 'Russie', code: 'RU' },
  'US': { name: 'Russie', code: 'RU' },
  'UT': { name: 'Tadjikistan/Turkménistan/Ouzbékistan', code: 'TJ' },
  'UU': { name: 'Russie', code: 'RU' },
  'UW': { name: 'Russie', code: 'RU' },
  
  // Afrique (D, F, G, H)
  'DA': { name: 'Algérie', code: 'DZ' },
  'DB': { name: 'Bénin', code: 'BJ' },
  'DF': { name: 'Burkina Faso', code: 'BF' },
  'DG': { name: 'Ghana', code: 'GH' },
  'DI': { name: 'Côte d\'Ivoire', code: 'CI' },
  'DN': { name: 'Nigeria', code: 'NG' },
  'DR': { name: 'Niger', code: 'NE' },
  'DT': { name: 'Tunisie', code: 'TN' },
  'DX': { name: 'Togo', code: 'TG' },
  'FA': { name: 'Afrique du Sud', code: 'ZA' },
  'FB': { name: 'Botswana', code: 'BW' },
  'FC': { name: 'République du Congo', code: 'CG' },
  'FD': { name: 'Eswatini', code: 'SZ' },
  'FE': { name: 'République centrafricaine', code: 'CF' },
  'FG': { name: 'Guinée équatoriale', code: 'GQ' },
  'FH': { name: 'Île de l\'Ascension', code: 'SH' },
  'FI': { name: 'Maurice', code: 'MU' },
  'FJ': { name: 'Territoire britannique de l\'océan Indien', code: 'IO' },
  'FK': { name: 'Cameroun', code: 'CM' },
  'FL': { name: 'Zambie', code: 'ZM' },
  'FM': { name: 'Comores/Madagascar/Mayotte/La Réunion', code: 'MG' },
  'FN': { name: 'Angola', code: 'AO' },
  'FO': { name: 'Gabon', code: 'GA' },
  'FP': { name: 'São Tomé-et-Principe', code: 'ST' },
  'FQ': { name: 'Mozambique', code: 'MZ' },
  'FS': { name: 'Seychelles', code: 'SC' },
  'FT': { name: 'Tchad', code: 'TD' },
  'FV': { name: 'Zimbabwe', code: 'ZW' },
  'FW': { name: 'Malawi', code: 'MW' },
  'FX': { name: 'Lesotho', code: 'LS' },
  'FY': { name: 'Namibie', code: 'NA' },
  'FZ': { name: 'République démocratique du Congo', code: 'CD' },
  'GA': { name: 'Mali', code: 'ML' },
  'GB': { name: 'Gambie', code: 'GM' },
  'GC': { name: 'Îles Canaries (Espagne)', code: 'ES' },
  'GE': { name: 'Ceuta et Melilla (Espagne)', code: 'ES' },
  'GF': { name: 'Sierra Leone', code: 'SL' },
  'GG': { name: 'Guinée-Bissau', code: 'GW' },
  'GL': { name: 'Liberia', code: 'LR' },
  'GM': { name: 'Maroc', code: 'MA' },
  'GO': { name: 'Sénégal', code: 'SN' },
  'GQ': { name: 'Mauritanie', code: 'MR' },
  'GS': { name: 'Sahara occidental', code: 'EH' },
  'GU': { name: 'Guinée', code: 'GN' },
  'GV': { name: 'Cap-Vert', code: 'CV' },
  'HA': { name: 'Éthiopie', code: 'ET' },
  'HB': { name: 'Burundi', code: 'BI' },
  'HC': { name: 'Somalie', code: 'SO' },
  'HD': { name: 'Djibouti', code: 'DJ' },
  'HE': { name: 'Égypte', code: 'EG' },
  'HF': { name: 'Djibouti', code: 'DJ' },
  'HH': { name: 'Érythrée', code: 'ER' },
  'HK': { name: 'Kenya', code: 'KE' },
  'HL': { name: 'Libye', code: 'LY' },
  'HR': { name: 'Rwanda', code: 'RW' },
  'HS': { name: 'Soudan', code: 'SD' },
  'HT': { name: 'Tanzanie', code: 'TZ' },
  'HU': { name: 'Ouganda', code: 'UG' },
  'HZ': { name: 'Soudan du Sud', code: 'SS' },
  
  // Amériques (C, K, M, S, T)
  'C': { name: 'Canada', code: 'CA' },
  'CU': { name: 'Canada', code: 'CA' },
  'CW': { name: 'Canada', code: 'CA' },
  'CY': { name: 'Canada', code: 'CA' },
  'CZ': { name: 'Canada', code: 'CA' },
  'K': { name: 'États-Unis (continental)', code: 'US' },
  'KA': { name: 'États-Unis (continental)', code: 'US' },
  'KB': { name: 'États-Unis (continental)', code: 'US' },
  'KC': { name: 'États-Unis (continental)', code: 'US' },
  'KD': { name: 'États-Unis (continental)', code: 'US' },
  'KE': { name: 'États-Unis (continental)', code: 'US' },
  'KF': { name: 'États-Unis (continental)', code: 'US' },
  'KG': { name: 'États-Unis (continental)', code: 'US' },
  'KH': { name: 'États-Unis (continental)', code: 'US' },
  'KI': { name: 'États-Unis (continental)', code: 'US' },
  'KJ': { name: 'États-Unis (continental)', code: 'US' },
  'KL': { name: 'États-Unis (continental)', code: 'US' },
  'KM': { name: 'États-Unis (continental)', code: 'US' },
  'KN': { name: 'États-Unis (continental)', code: 'US' },
  'KO': { name: 'États-Unis (continental)', code: 'US' },
  'KP': { name: 'États-Unis (continental)', code: 'US' },
  'KR': { name: 'États-Unis (continental)', code: 'US' },
  'KS': { name: 'États-Unis (continental)', code: 'US' },
  'KT': { name: 'États-Unis (continental)', code: 'US' },
  'KU': { name: 'États-Unis (continental)', code: 'US' },
  'KV': { name: 'États-Unis (continental)', code: 'US' },
  'KW': { name: 'États-Unis (continental)', code: 'US' },
  'KX': { name: 'États-Unis (continental)', code: 'US' },
  'KY': { name: 'États-Unis (continental)', code: 'US' },
  'KZ': { name: 'États-Unis (continental)', code: 'US' },
  'MB': { name: 'Îles Turques-et-Caïques', code: 'TC' },
  'MD': { name: 'République dominicaine', code: 'DO' },
  'MG': { name: 'Guatemala', code: 'GT' },
  'MH': { name: 'Honduras', code: 'HN' },
  'MK': { name: 'Jamaïque', code: 'JM' },
  'MM': { name: 'Mexique', code: 'MX' },
  'MN': { name: 'Nicaragua', code: 'NI' },
  'MP': { name: 'Panama', code: 'PA' },
  'MR': { name: 'Costa Rica', code: 'CR' },
  'MS': { name: 'Salvador', code: 'SV' },
  'MT': { name: 'Haïti', code: 'HT' },
  'MU': { name: 'Cuba', code: 'CU' },
  'MW': { name: 'Îles Caïmans', code: 'KY' },
  'MY': { name: 'Bahamas', code: 'BS' },
  'MZ': { name: 'Belize', code: 'BZ' },
  'PA': { name: 'Alaska', code: 'US' },
  'PF': { name: 'Alaska', code: 'US' },
  'PG': { name: 'Îles Mariannes du Nord/Guam', code: 'MP' },
  'PH': { name: 'Hawaï', code: 'US' },
  'PJ': { name: 'Atoll Johnston', code: 'UM' },
  'PO': { name: 'Alaska', code: 'US' },
  'PP': { name: 'Alaska', code: 'US' },
  'SA': { name: 'Argentine', code: 'AR' },
  'SB': { name: 'Brésil', code: 'BR' },
  'SC': { name: 'Chili', code: 'CL' },
  'SD': { name: 'Brésil', code: 'BR' },
  'SE': { name: 'Équateur', code: 'EC' },
  'SF': { name: 'Îles Malouines', code: 'FK' },
  'SG': { name: 'Paraguay', code: 'PY' },
  'SK': { name: 'Colombie', code: 'CO' },
  'SL': { name: 'Bolivie', code: 'BO' },
  'SM': { name: 'Suriname', code: 'SR' },
  'SO': { name: 'Guyane française', code: 'GF' },
  'SP': { name: 'Pérou', code: 'PE' },
  'SU': { name: 'Uruguay', code: 'UY' },
  'SV': { name: 'Venezuela', code: 'VE' },
  'SY': { name: 'Guyana', code: 'GY' },
  'TA': { name: 'Antigua-et-Barbuda', code: 'AG' },
  'TB': { name: 'Barbade', code: 'BB' },
  'TD': { name: 'Dominique', code: 'DM' },
  'TF': { name: 'Guadeloupe/Martinique', code: 'GP' },
  'TG': { name: 'Grenade', code: 'GD' },
  'TI': { name: 'Îles Vierges des États-Unis', code: 'VI' },
  'TJ': { name: 'Porto Rico', code: 'PR' },
  'TK': { name: 'Saint-Christophe-et-Niévès', code: 'KN' },
  'TL': { name: 'Sainte-Lucie', code: 'LC' },
  'TN': { name: 'Antilles néerlandaises/Aruba', code: 'AN' },
  'TQ': { name: 'Anguilla', code: 'AI' },
  'TR': { name: 'Montserrat', code: 'MS' },
  'TT': { name: 'Trinité-et-Tobago', code: 'TT' },
  'TU': { name: 'Îles Vierges britanniques', code: 'VG' },
  'TV': { name: 'Saint-Vincent-et-les-Grenadines', code: 'VC' },
  'TX': { name: 'Bermudes', code: 'BM' },
  
  // Océanie et Pacifique (A, N, P, Y, Z)
  'AF': { name: 'Terres australes et antarctiques françaises', code: 'TF' },
  'AG': { name: 'Îles Salomon', code: 'SB' },
  'AN': { name: 'Nauru', code: 'NR' },
  'AY': { name: 'Papouasie-Nouvelle-Guinée', code: 'PG' },
  'BG': { name: 'Groenland', code: 'GL' },
  'BI': { name: 'Islande', code: 'IS' },
  'NC': { name: 'Îles Cook', code: 'CK' },
  'NF': { name: 'Fidji/Tonga', code: 'FJ' },
  'NG': { name: 'Tuvalu', code: 'TV' },
  'NI': { name: 'Niue', code: 'NU' },
  'NL': { name: 'Wallis-et-Futuna', code: 'WF' },
  'NS': { name: 'Samoa', code: 'WS' },
  'NT': { name: 'Polynésie française', code: 'PF' },
  'NV': { name: 'Vanuatu', code: 'VU' },
  'NW': { name: 'Nouvelle-Calédonie', code: 'NC' },
  'NZ': { name: 'Nouvelle-Zélande', code: 'NZ' },
  'PB': { name: 'Île Baker', code: 'UM' },
  'PC': { name: 'Îles Phoenix/Kiribati', code: 'KI' },
  'PK': { name: 'Îles Marshall', code: 'MH' },
  'PL': { name: 'Kiribati', code: 'KI' },
  'PM': { name: 'Îles Midway', code: 'UM' },
  'PT': { name: 'États fédérés de Micronésie/Palaos', code: 'FM' },
  'PW': { name: 'Îles de Wake', code: 'UM' },
  'WA': { name: 'Indonésie', code: 'ID' },
  'WB': { name: 'Malaisie/Brunei', code: 'MY' },
  'WI': { name: 'Papouasie occidentale (Indonésie)', code: 'ID' },
  'WM': { name: 'Malaisie', code: 'MY' },
  'WP': { name: 'Timor oriental', code: 'TL' },
  'WQ': { name: 'Indonésie', code: 'ID' },
  'WR': { name: 'Bali (Indonésie)', code: 'ID' },
  'WS': { name: 'Singapour', code: 'SG' },
  'Y': { name: 'Australie', code: 'AU' },
  'YA': { name: 'Australie', code: 'AU' },
  'YB': { name: 'Australie', code: 'AU' },
  'YC': { name: 'Australie', code: 'AU' },
  'YD': { name: 'Australie', code: 'AU' },
  'YE': { name: 'Australie', code: 'AU' },
  'YF': { name: 'Australie', code: 'AU' },
  'YG': { name: 'Australie', code: 'AU' },
  'YH': { name: 'Australie', code: 'AU' },
  'YI': { name: 'Australie', code: 'AU' },
  'YJ': { name: 'Australie', code: 'AU' },
  'YK': { name: 'Australie', code: 'AU' },
  'YL': { name: 'Australie', code: 'AU' },
  'YM': { name: 'Australie', code: 'AU' },
  'YN': { name: 'Australie', code: 'AU' },
  'YO': { name: 'Australie', code: 'AU' },
  'YP': { name: 'Australie', code: 'AU' },
  'YQ': { name: 'Australie', code: 'AU' },
  'YR': { name: 'Australie', code: 'AU' },
  'YS': { name: 'Australie', code: 'AU' },
  'YT': { name: 'Australie', code: 'AU' },
  'YW': { name: 'Australie', code: 'AU' },
  'YY': { name: 'Australie', code: 'AU' },
  'Z': { name: 'Chine', code: 'CN' },
  'ZB': { name: 'Chine continentale', code: 'CN' },
  'ZG': { name: 'Chine continentale', code: 'CN' },
  'ZH': { name: 'Chine continentale', code: 'CN' },
  'ZK': { name: 'Corée du Nord', code: 'KP' },
  'ZL': { name: 'Chine continentale', code: 'CN' },
  'ZM': { name: 'Mongolie', code: 'MN' },
  'ZP': { name: 'Chine continentale', code: 'CN' },
  'ZS': { name: 'Chine continentale', code: 'CN' },
  'ZU': { name: 'Chine continentale', code: 'CN' },
  'ZW': { name: 'Chine continentale', code: 'CN' },
  'ZY': { name: 'Chine continentale', code: 'CN' }
};

/**
 * Fonction pour obtenir le nom du pays à partir du code OACI (2 lettres)
 */
export const getCountryNameFromOACI = (code: string): string => {
  if (countriesOACI[code]) {
    return countriesOACI[code].name;
  }
  return `Code ${code}`;
}; 